[2024-01-01]  # 2024-07-12 – 2024-07-20
VehicleSpeed = ["VehicleVelocity", "MDI", "m/s", 5]
PackVoltage = ["TotalPackVoltage", "BMS", "V", 1]
PackCurrent = ["PackCurrent", "ECU", "A", 5]
MotorCurrent = ["BatteryCurrent", "MC", "A", 5]
AcceleratorPosition = ["AcceleratorPosition", "MC", "", 10]
MinimumModuleVoltage = ["VoltageofLeast", "BMS","V", 1]
MaximumModuleVoltage = ["VoltageofHighest", "BMS", "V", 1]
BrakePressed = ["MechBrakePressed", "MCB", "", 10]
MotorCurrentDirection = ["BatteryCurrentDirection", "MC", "", 5]

MPPTInputVoltageA = ["VoltSensor1", "AMB", "V", 4]
MPPTInputVoltageB = ["VoltSensor2", "AMB", "V", 4]
MPPTInputCurrentA = ["CurrentSensor1", "AMB", "A", 4]
MPPTInputCurrentB = ["CurrentSensor2", "AMB", "A", 4]


[2025-01-01]  # 2025-04-01 – 2025-07-23
VehicleSpeed = ["MotorRotatingSpeed", "MC", "km/h", 10]
PackVoltage = ["TotalPackVoltage", "BMS", "V", 10]
PackCurrent = ["PackCurrent", "ECU", "A", 5]
MotorCurrent = ["BatteryCurrent", "MC", "A", 10]
AcceleratorPosition = ["AcceleratorPosition", "MC", "", 10]
MinimumModuleVoltage = ["VoltageofLeast", "BMS","V", 10]
MaximumModuleVoltage = ["VoltageofHighest", "BMS", "V", 10]
BrakePressed = ["BrakePressed", "DRD", "", 10]
MotorCurrentDirection = ["BatteryCurrentDirection", "MC", "", 10]

MPPTOutputVoltageA = ["OutputVoltageA", "MPPT", "V", 3]
MPPTOutputVoltageB = ["OutputVoltageB", "MPPT", "V", 3]
MPPTOutputVoltageC = ["OutputVoltageC", "MPPT", "V", 3]
MPPTOutputCurrentA = ["OutputCurrentA", "MPPT", "A", 3]
MPPTOutputCurrentB = ["OutputCurrentB", "MPPT", "A", 3]
MPPTOutputCurrentC = ["OutputCurrentC", "MPPT", "A", 3]

MPPTInputVoltageA = ["InputVoltageA", "MPPT", "V", 3]
MPPTInputVoltageB = ["InputVoltageB", "MPPT", "V", 3]
MPPTInputVoltageC = ["InputVoltageC", "MPPT", "V", 3]
MPPTInputCurrentA = ["InputCurrentA", "MPPT", "A", 3]
MPPTInputCurrentB = ["InputCurrentB", "MPPT", "A", 3]
MPPTInputCurrentC = ["InputCurrentC", "MPPT", "A", 3]

GPSLatitude = ["GPSLatitude", "TEL", "", 3]
GPSLongitude = ["GPSLongitude", "TEL", "", 3]

Acceleration_X = ["Acceleration_X", "TEL", "", 10]
Acceleration_Y = ["Acceleration_Y", "TEL", "", 10]
Acceleration_Z = ["Acceleration_Z", "TEL", "", 10]


[2026-01-01]   # 2026-01-20 –
VehicleSpeed = ["MotorRotatingSpeed", "MC", "km/h", 10]
PackVoltage = ["TotalPackVoltage", "BMS", "V", 10]
PackCurrent = ["PackCurrent", "ECU", "A", 5]
MotorCurrent = ["BatteryCurrent", "MC", "A", 10]
AcceleratorPosition = ["AcceleratorPosition", "MC", "", 10]
MinimumModuleVoltage = ["VoltageofLeast", "BMS", "V", 10]
MaximumModuleVoltage = ["VoltageofHighest", "BMS", "V", 10]
BrakePressed = ["BrakePressed", "DRD", "", 10]
MotorCurrentDirection = ["BatteryCurrentDirection", "MC", "", 10]

MPPTOutputVoltageA = ["OutputVoltageA", "MPPT", "V", 3]
MPPTOutputVoltageB = ["OutputVoltageB", "MPPT", "V", 3]
MPPTOutputVoltageC = ["OutputVoltageC", "MPPT", "V", 3]
MPPTOutputCurrentA = ["OutputCurrentA", "MPPT", "A", 3]
MPPTOutputCurrentB = ["OutputCurrentB", "MPPT", "A", 3]
MPPTOutputCurrentC = ["OutputCurrentC", "MPPT", "A", 3]

MPPTInputVoltageA = ["InputVoltageA", "MPPT", "V", 3]
MPPTInputVoltageB = ["InputVoltageB", "MPPT", "V", 3]
MPPTInputVoltageC = ["InputVoltageC", "MPPT", "V", 3]
MPPTInputCurrentA = ["InputCurrentA", "MPPT", "A", 3]
MPPTInputCurrentB = ["InputCurrentB", "MPPT", "A", 3]
MPPTInputCurrentC = ["InputCurrentC", "MPPT", "A", 3]

GPSLatitude = ["GPSLatitude", "TEL", "", 4]
GPSLongitude = ["GPSLongitude", "TEL", "", 4]

Acceleration_X = ["Acceleration_X", "TEL", "", 10]
Acceleration_Y = ["Acceleration_Y", "TEL", "", 10]
Acceleration_Z = ["Acceleration_Z", "TEL", "", 10]
