# CanonicalName = [SunbeamDB Signal, stage_name, unit, frequency]
[2024-01-01]  # 2024-07-12 – 2024-07-20
VehicleSpeed = ["VehicleSpeed", "Ingress", "m/s", 5]
PackVoltage = ["PackVoltage", "Ingress", "V", 1]
PackCurrent = ["PackCurrent", "Ingress", "A", 5]
MotorCurrent = ["MotorCurrent", "Ingress", "A", 5]
MotorCurrentDirection = ["MotorCurrentDirection", "Ingress", "", 5]
AcceleratorPosition = ["AcceleratorPosition", "Ingress", "", 10]
MinimumModuleVoltage = ["MinimumModuleVoltage", "Ingress","V", 1]
MaximumModuleVoltage = ["MaximumModuleVoltage", "Ingress", "V", 1]
BrakePressed = ["BrakePressed", "Ingress", "", 10]
MotorEfficiency = ["MotorEfficiency", "Efficiency", "", 1]

MPPTInputVoltageA = ["MPPTInputVoltageA", "Ingress", "V", 4]
MPPTInputVoltageB = ["MPPTInputVoltageB", "Ingress", "V", 4]
MPPTInputCurrentA = ["MPPTInputCurrentA", "Ingress", "A", 4]
MPPTInputCurrentB = ["MPPTInputCurrentB", "Ingress", "A", 4]

ArrayPower = ["ArrayPower", "Array", "W", 4]
MotorPower = ["MotorPower", "MotorPower", "W", 10]
PackPower = ["PackPower", "PackPower","W", 5]

IntegratedPackPower = ["IntegratedPackPower", "IntegratedPackPower", "Wh", 5]
EnergyVOLExtrapolated = ["EnergyVOLExtrapolated", "EnergyVOLExtrapolated", "Wh", 10]
EnergyFromIntegratedPower = ["EnergyFromIntegratedPower", "EnergyFromIntegratedPower", "Wh", 5]

LatitudeRaw = ["LatitudeRaw", "TEL", "", 3]
LongitudeRaw = ["LongitudeRaw", "TEL", "", 3]
LatitudeFiltered = ["LatitudeFiltered", "LatitudeLongitude", "", 3]
LongitudeFiltered = ["LongitudeFiltered", "LatitudeLongitude", "", 3]



#[2025-01-01]  # 2025-04-01 – 2025-07-23
#VehicleSpeed = ["MotorRotatingSpeed", "MC", "km/h", 10]
#PackVoltage = ["TotalPackVoltage", "BMS", "V", 10]
#PackCurrent = ["PackCurrent", "ECU", "A", 5]
#MotorCurrent = ["BatteryCurrent", "MC", "A", 10]
#AcceleratorPosition = ["AcceleratorPosition", "MC", "", 10]
#MinimumModuleVoltage = ["VoltageofLeast", "BMS","V", 10]
#MaximumModuleVoltage = ["VoltageofHighest", "BMS", "V", 10]
#BrakePressed = ["BrakePressed", "DRD", "", 10]
#MotorCurrentDirection = ["BatteryCurrentDirection", "MC", "", 10]
#
#MPPTOutputVoltageA = ["OutputVoltageA", "MPPT", "V", 3]
#MPPTOutputVoltageB = ["OutputVoltageB", "MPPT", "V", 3]
#MPPTOutputVoltageC = ["OutputVoltageC", "MPPT", "V", 3]
#MPPTOutputCurrentA = ["OutputCurrentA", "MPPT", "A", 3]
#MPPTOutputCurrentB = ["OutputCurrentB", "MPPT", "A", 3]
#MPPTOutputCurrentC = ["OutputCurrentC", "MPPT", "A", 3]
#
#MPPTInputVoltageA = ["InputVoltageA", "MPPT", "V", 3]
#MPPTInputVoltageB = ["InputVoltageB", "MPPT", "V", 3]
#MPPTInputVoltageC = ["InputVoltageC", "MPPT", "V", 3]
#MPPTInputCurrentA = ["InputCurrentA", "MPPT", "A", 3]
#MPPTInputCurrentB = ["InputCurrentB", "MPPT", "A", 3]
#MPPTInputCurrentC = ["InputCurrentC", "MPPT", "A", 3]
#
#GPSLatitude = ["GPSLatitude", "TEL", "", 3]
#GPSLongitude = ["GPSLongitude", "TEL", "", 3]
#
#Acceleration_X = ["Acceleration_X", "TEL", "", 10]
#Acceleration_Y = ["Acceleration_Y", "TEL", "", 10]
#Acceleration_Z = ["Acceleration_Z", "TEL", "", 10]
#
#
#[2026-01-01]   # 2026-01-20 –
#VehicleSpeed = ["MotorRotatingSpeed", "MC", "km/h", 10]
#PackVoltage = ["TotalPackVoltage", "BMS", "V", 10]
#PackCurrent = ["PackCurrent", "ECU", "A", 5]
#MotorCurrent = ["BatteryCurrent", "MC", "A", 10]
#AcceleratorPosition = ["AcceleratorPosition", "MC", "", 10]
#MinimumModuleVoltage = ["VoltageofLeast", "BMS", "V", 10]
#MaximumModuleVoltage = ["VoltageofHighest", "BMS", "V", 10]
#BrakePressed = ["BrakePressed", "DRD", "", 10]
#MotorCurrentDirection = ["BatteryCurrentDirection", "MC", "", 10]
#
#MPPTOutputVoltageA = ["OutputVoltageA", "MPPT", "V", 3]
#MPPTOutputVoltageB = ["OutputVoltageB", "MPPT", "V", 3]
#MPPTOutputVoltageC = ["OutputVoltageC", "MPPT", "V", 3]
#MPPTOutputCurrentA = ["OutputCurrentA", "MPPT", "A", 3]
#MPPTOutputCurrentB = ["OutputCurrentB", "MPPT", "A", 3]
#MPPTOutputCurrentC = ["OutputCurrentC", "MPPT", "A", 3]
#
#MPPTInputVoltageA = ["InputVoltageA", "MPPT", "V", 3]
#MPPTInputVoltageB = ["InputVoltageB", "MPPT", "V", 3]
#MPPTInputVoltageC = ["InputVoltageC", "MPPT", "V", 3]
#MPPTInputCurrentA = ["InputCurrentA", "MPPT", "A", 3]
#MPPTInputCurrentB = ["InputCurrentB", "MPPT", "A", 3]
#MPPTInputCurrentC = ["InputCurrentC", "MPPT", "A", 3]
#
#GPSLatitude = ["GPSLatitude", "TEL", "", 4]
#GPSLongitude = ["GPSLongitude", "TEL", "", 4]
#
#Acceleration_X = ["Acceleration_X", "TEL", "", 10]
#Acceleration_Y = ["Acceleration_Y", "TEL", "", 10]
#Acceleration_Z = ["Acceleration_Z", "TEL", "", 10]
