# This workflow is maintained according to STG Specification #2: Physics Publishing

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        python -m pip install poetry==1.8.3

    - name: Configure Poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Cache the Virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: |
        python -m poetry install --with test

    - name: Run Tests
      run: |
        python -m poetry run pytest --cov --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}



